repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pipreqs
        name: Run pipreqs
        entry: sh -c "pipreqs . --force"
        language: system
      - id: git
        name: Run git add
        entry: sh -c "git add ."
        language: system
